# Generated by Django 3.1 on 2020-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_post_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
