# Generated by Django 3.1 on 2020-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_post_amount_of_upvotes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="author_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
